### ISSUE TITLE
Usage outside of DefinitelyTyped

### ISSUE THREAD

**Issue by tomasz-zablocki** [andrewbranch/definitely-not-slow#29]
First of all, congrats for this impressive tool.

I'd like to know whether it can be used outside of DefinitelyTyped ecosystem. 

To be specific, I'd like to use it to obtain the metrics generated for DefinitelyTyped PR, but for a  local types package instead.

**Comment by andrewbranch** [comment]
Hey @tomasz-zablocki, sorry for the delayed response. Currently DefinitelyTyped is kind of hard-wired into this tool, but it’s fairly modular if you wanted to adapt some of the existing code. The majority of the metrics are gathered [here](https://github.com/andrewbranch/definitely-not-slow/blob/master/src/measure/measureLanguageServiceWorker.ts) and by that point, it’s no longer specific to DefinitelyTyped at all.

**Comment by tomasz-zablocki** [comment]
@andrewbranch Thank you very much, I'll try to adapt parts of it to my needs then.
