### ISSUE TITLE
For PRs, run against master when type's external dependency is updated

### ISSUE THREAD

**Issue by devrelm** [andrewbranch/definitely-not-slow#49]
Some types rely on non-DefinitelyTyped types. For instance [`@types/ramda`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ramda) depends on [`ts-toolbelt`](https://npmjs.com/package/ts-toolbelt). Updates to these external dependencies (especially utility-types packages like `ts-toolbelt`) could cause large changes to the benchmarks for a DefinitelyTyped type that are unrelated to the changes made for the PR.

I propose modifying the [2nd item in the "Usage" list](https://github.com/andrewbranch/definitely-not-slow/blob/a79c3125189b2e08e1cae493a396adee1c38c504/README.md#usage), to specify that "aren’t up-to-date" includes packages whose last benchmark used an older version of their dependencies.

This would require a few updates:

1. Storing the version of each dependency used when persisting a benchmark
2. Retrieving the version of each dependency for the prior benchmark
3. In `compareBenchmarks`, we'd want to check the if the current versions of each dependency (that still matches the semver) is not the same as the stored versions. If a version has changed, then we'd want to run a new benchmark for the package against `origin/master` and compare against that benchmark.
   * This could get complicated. There would be times when a package's external dependencies have been updated _because the dependency's semver version was updated in `package.json`_. For instance, to enforce an older version when the current version is broken, or to update to a new major version. In those cases we may or may not want to run the prior benchmark.

     This part is probably worth a bit of discussion below.

**Comment by andrewbranch** [comment]
This repo has moved to https://github.com/microsoft/DefinitelyTyped-tools/tree/master/packages/perf. Your idea is good, but GitHub won’t let me transfer issues across owners, and frankly there are bigger problems with this tooling that I also don’t currently have time to fix. If it’s something you’re still interested in, feel free to reopen an issue there. Thanks!
